from flask import Flask, render_template, jsonify
import pickle
import pandas as pd
import os
from google.cloud import bigquery
import logging
from sklearn.preprocessing import OneHotEncoder

app = Flask(__name__)

# Initialize BigQuery client
try:
    bq_client = bigquery.Client()
except Exception as e:
    app.logger.error(f"Error initializing BigQuery client: {str(e)}")

# Load the pre-trained model
model_path = os.path.join('models', 'prelim_rf_model.pkl')
try:
    with open(model_path, 'rb') as file:
        model = pickle.load(file)
except Exception as e:
    app.logger.error(f"Error loading model: {str(e)}")
    model = None

# State electoral votes
states_dict = {
    'Alabama': 9, 'Alaska': 3, 'Arizona': 11, 'Arkansas': 6, 'California': 54,
    'Colorado': 10, 'Connecticut': 7, 'Delaware': 3, 'Florida': 30, 'Georgia': 16,
    'Hawaii': 4, 'Idaho': 4, 'Illinois': 19, 'Indiana': 11, 'Iowa': 6, 'Kansas': 6,
    'Kentucky': 8, 'Louisiana': 8, 'Maine': 4, 'Maryland': 10, 'Massachusetts': 11,
    'Michigan': 15, 'Minnesota': 10, 'Mississippi': 6, 'Missouri': 10, 'Montana': 4,
    'Nebraska': 5, 'Nevada': 6, 'New Hampshire': 4, 'New Jersey': 14, 'New Mexico': 5,
    'New York': 28, 'North Carolina': 16, 'North Dakota': 3, 'Ohio': 17, 'Oklahoma': 7,
    'Oregon': 8, 'Pennsylvania': 19, 'Rhode Island': 4, 'South Carolina': 9, 'South Dakota': 3,
    'Tennessee': 11, 'Texas': 40, 'Utah': 6, 'Vermont': 3, 'Virginia': 13, 'Washington': 12,
    'West Virginia': 4, 'Wisconsin': 10, 'Wyoming': 3, 'District of Columbia': 3
}

@app.route('/')
def home():
    try:
        # Define your BigQuery SQL query
        query = """
            SELECT tnr.state AS state,
tnr.ReportedTotalPeople AS TOTALNumberOfRacesReportedTotalPeople,
tnr.ReportedTotalPeopleOneRaceInPercent AS TOTALNumberOfRacesReportedTotalPeopleOneRaceInPercent,
tnr.ReportedTotalPeopleTwoRacesInPercent AS TOTALNumberOfRacesReportedTotalPeopleTwoRacesInPercent,
tnr.ReportedTotalPeopleThreeRacesInPercent AS TOTALNumberOfRacesReportedTotalPeopleThreeRacesInPercent,
tnr.ReportedTotalPeopleFourOrMoreRacesInPercent AS TOTALNumberOfRacesReportedTotalPeopleFourOrMoreRacesInPercent,
saa.TotalPeople AS SEXAndAgeTotalPeople,
saa.TotalPeopleMaleInPercent AS SEXAndAgeTotalPeopleMaleInPercent,
saa.TotalPeopleFemaleInPercent AS SEXAndAgeTotalPeopleFemaleInPercent,
saa.TotalPeopleUnder5YearsInPercent AS SEXAndAgeTotalPeopleUnder5YearsInPercent,
saa.TotalPeople5To17YearsInPercent AS SEXAndAgeTotalPeople5To17YearsInPercent,
saa.TotalPeople18To24YearsInPercent AS SEXAndAgeTotalPeople18To24YearsInPercent,
saa.TotalPeople25To34YearsInPercent AS SEXAndAgeTotalPeople25To34YearsInPercent,
saa.TotalPeople35To44YearsInPercent AS SEXAndAgeTotalPeople35To44YearsInPercent,
saa.TotalPeople45To54YearsInPercent AS SEXAndAgeTotalPeople45To54YearsInPercent,
saa.TotalPeople55To64YearsInPercent AS SEXAndAgeTotalPeople55To64YearsInPercent,
saa.TotalPeople65To74YearsInPercent AS SEXAndAgeTotalPeople65To74YearsInPercent,
saa.TotalPeople75YearsAndOverInPercent AS SEXAndAgeTotalPeople75YearsAndOverInPercent,
saa.TotalPeopleMedianAge_Years_ AS SEXAndAgeTotalPeopleMedianAge_Years_,
saa.TotalPeople18YearsAndOverInPercent AS SEXAndAgeTotalPeople18YearsAndOverInPercent,
saa.TotalPeople21YearsAndOverInPercent AS SEXAndAgeTotalPeople21YearsAndOverInPercent,
saa.TotalPeople62YearsAndOverInPercent AS SEXAndAgeTotalPeople62YearsAndOverInPercent,
saa.TotalPeople65YearsAndOverInPercent AS SEXAndAgeTotalPeople65YearsAndOverInPercent,
saa.TotalPeopleUnder18Years AS SEXAndAgeTotalPeopleUnder18Years,
saa.TotalPeopleUnder18YearsMaleInPercent AS SEXAndAgeTotalPeopleUnder18YearsMaleInPercent,
saa.TotalPeopleUnder18YearsFemaleInPercent AS SEXAndAgeTotalPeopleUnder18YearsFemaleInPercent,
saa.TotalPeople18YearsAndOver1 AS SEXAndAgeTotalPeople18YearsAndOver1,
saa.TotalPeople18YearsAndOverMaleInPercent AS SEXAndAgeTotalPeople18YearsAndOverMaleInPercent,
saa.TotalPeople18YearsAndOverFemaleInPercent AS SEXAndAgeTotalPeople18YearsAndOverFemaleInPercent,
saa.TotalPeople18To34Years AS SEXAndAgeTotalPeople18To34Years,
saa.TotalPeople18To34YearsMaleInPercent AS SEXAndAgeTotalPeople18To34YearsMaleInPercent,
saa.TotalPeople18To34YearsFemaleInPercent AS SEXAndAgeTotalPeople18To34YearsFemaleInPercent,
saa.TotalPeople35To64Years AS SEXAndAgeTotalPeople35To64Years,
saa.TotalPeople35To64YearsMaleInPercent AS SEXAndAgeTotalPeople35To64YearsMaleInPercent,
saa.TotalPeople35To64YearsFemaleInPercent AS SEXAndAgeTotalPeople35To64YearsFemaleInPercent,
saa.TotalPeople65YearsAndOver1 AS SEXAndAgeTotalPeople65YearsAndOver1,
saa.TotalPeople65YearsAndOverMaleInPercent AS SEXAndAgeTotalPeople65YearsAndOverMaleInPercent,
saa.TotalPeople65YearsAndOverFemaleInPercent AS SEXAndAgeTotalPeople65YearsAndOverFemaleInPercent,
rel.PeopleInHouseholds AS RELATIONSHIPPeopleInHouseholds,
rel.PeopleInHouseholdsHouseholderOrSpouseInPercent AS RELATIONSHIPPeopleInHouseholdsHouseholderOrSpouseInPercent,
rel.PeopleInHouseholdsUnmarriedPartnerInPercent AS RELATIONSHIPPeopleInHouseholdsUnmarriedPartnerInPercent,
rel.PeopleInHouseholdsChildInPercent AS RELATIONSHIPPeopleInHouseholdsChildInPercent,
rel.PeopleInHouseholdsOtherRelativesInPercent AS RELATIONSHIPPeopleInHouseholdsOtherRelativesInPercent,
rel.PeopleInHouseholdsOtherNonrelativesInPercent AS RELATIONSHIPPeopleInHouseholdsOtherNonrelativesInPercent,
hbt.HOUSEHOLDSByTypeHouseholds AS HOUSEHOLDSByTypeHouseholds,
hbt.FamilyHouseholdsInPercent AS HOUSEHOLDSByTypeHouseholdsFamilyHouseholdsInPercent,
hbt.FamilyWithOwnChildrenUnder18YearsInPercent AS HOUSEHOLDSByTypeHouseholdsFamilyHouseholdsWithOwnChildrenOfTheHouseholderUnder18YearsInPercent,
hbt.Married_CoupleFamilyPercent AS HOUSEHOLDSByTypeHouseholdsMarried_CoupleFamilyInPercent,
hbt.Married_CoupleWithChildrenUnder18YearsInPercent AS HOUSEHOLDSByTypeHouseholdsMarried_CoupleFamilyWithOwnChildrenOfTheHouseholderUnder18YearsInPercent,
hbt.FemaleHouseholderNoSpousePresentPercent AS HOUSEHOLDSByTypeHouseholdsFemaleHouseholderNoSpousePresentFamilyInPercent,
hbt.FemaleHouseholderNoSpouseWithChildUnder18Percent AS HOUSEHOLDSByTypeHouseholdsFemaleHouseholderNoSpousePresentFamilyWithOwnChildrenOfTheHouseholderUnder18YearsInPercent,
hbt.NonfamilyHouseholdsInPercent AS HOUSEHOLDSByTypeHouseholdsNonfamilyHouseholdsInPercent,
hbt.NonfamilyHouseholdsMaleHouseholderInPercent AS HOUSEHOLDSByTypeHouseholdsNonfamilyHouseholdsMaleHouseholderInPercent,
hbt.NonfamilyMaleHouseholderLivingAloneInPercent AS HOUSEHOLDSByTypeHouseholdsNonfamilyHouseholdsMaleHouseholderLivingAloneInPercent,
hbt.NonfamilyMaleHouseholderNotLivingAloneInPercent AS HOUSEHOLDSByTypeHouseholdsNonfamilyHouseholdsMaleHouseholderNotLivingAloneInPercent,
hbt.NonfamilyHouseholdsFemaleHouseholderInPercent AS HOUSEHOLDSByTypeHouseholdsNonfamilyHouseholdsFemaleHouseholderInPercent,
hbt.NonfamilyFemaleHouseholderLivingAloneInPercent AS HOUSEHOLDSByTypeHouseholdsNonfamilyHouseholdsFemaleHouseholderLivingAloneInPercent,
hbt.NonfamilyFemaleHouseholderNotLivingAloneInPercent AS HOUSEHOLDSByTypeHouseholdsNonfamilyHouseholdsFemaleHouseholderNotLivingAloneInPercent,
hbt.AverageHouseholdSize AS HOUSEHOLDSByTypeHouseholdsAverageHouseholdSize,
hbt.AverageFamilySize AS HOUSEHOLDSByTypeHouseholdsAverageFamilySize,
mar.People15YearsAndOver AS MARITALStatusPeople15YearsAndOver,
mar.People15YearsNOverNowMarriedExcepSeparatedPercent AS MARITALStatusPeople15YearsAndOverNowMarriedExceptSeparatedInPercent,
mar.People15YearsAndOverWidowedInPercent AS MARITALStatusPeople15YearsAndOverWidowedInPercent,
mar.People15YearsAndOverDivorcedInPercent AS MARITALStatusPeople15YearsAndOverDivorcedInPercent,
mar.People15YearsAndOverSeparatedInPercent AS MARITALStatusPeople15YearsAndOverSeparatedInPercent,
mar.People15YearsAndOverNeverMarriedInPercent AS MARITALStatusPeople15YearsAndOverNeverMarriedInPercent,
mar.Male15YearsAndOver AS MARITALStatusMale15YearsAndOver,
mar.Male15YearAndOverNowMarriedExceptSeparatedPercent AS MARITALStatusMale15YearAndOverNowMarriedExceptSeparatedInPercent,
mar.Male15YearsAndOverWidowedInPercent AS MARITALStatusMale15YearsAndOverWidowedInPercent,
mar.Male15YearsAndOverDivorcedInPercent AS MARITALStatusMale15YearsAndOverDivorcedInPercent,
mar.Male15YearsAndOverSeparatedInPercent AS MARITALStatusMale15YearsAndOverSeparatedInPercent,
mar.Male15YearsAndOverNeverMarriedInPercent AS MARITALStatusMale15YearsAndOverNeverMarriedInPercent,
mar.Female15YearsAndOver AS MARITALStatusFemale15YearsAndOver,
mar.Female15YearNOverNowMarriedExceptSeparatedPercent AS MARITALStatusFemale15YearsAndOverNowMarriedExceptSeparatedInPercent,
mar.Female15YearsAndOverWidowedInPercent AS MARITALStatusFemale15YearsAndOverWidowedInPercent,
mar.Female15YearsAndOverDivorcedInPercent AS MARITALStatusFemale15YearsAndOverDivorcedInPercent,
mar.Female15YearsAndOverSeparatedInPercent AS MARITALStatusFemale15YearsAndOverSeparatedInPercent,
mar.Female15YearsAndOverNeverMarriedInPercent AS MARITALStatusFemale15YearsAndOverNeverMarriedInPercent,
seop.EnrolledInSchool AS SCHOOLEnrollmentPeople3YearsAndOverEnrolledInSchool,
seop.EnrolledInSchoolNurserySchoolPreschoolInPercent AS SCHOOLEnrollmentPeople3YearsAndOverEnrolledInSchoolNurserySchoolPreschoolInPercent,
seop.EnrolledInSchoolKindergartenInPercent AS SCHOOLEnrollmentPeople3YearsAndOverEnrolledInSchoolKindergartenInPercent,
seop.EnrolledInSchoolElementarySchoolGrade1_8InPercent AS SCHOOLEnrollmentPeople3YearsAndOverEnrolledInSchoolElementarySchool_Grades1_8_InPercent,
seop.EnrolledInSchoolHighSchool_Grades9_12_InPercent AS SCHOOLEnrollmentPeople3YearsAndOverEnrolledInSchoolHighSchool_Grades9_12_InPercent,
seop.EnrolledInSchoolCollegeOrGraduateSchoolInPercent AS SCHOOLEnrollmentPeople3YearsAndOverEnrolledInSchoolCollegeOrGraduateSchoolInPercent,
seop.Male AS SCHOOLEnrollmentPeople3YearsAndOverEnrolledInSchoolMale3YearsAndOverEnrolledInSchool,
seop.MalePercentEnrolledInKindergartenTo12InPercent AS SCHOOLEnrollmentPeople3YearsAndOverEnrolledInSchoolMale3YearsAndOverEnrolledInSchoolPercentEnrolledInKindergartenToGrade12InPercent,
seop.MaleEnrolledInCollegeOrGraduateSchoolInPercent AS SCHOOLEnrollmentPeople3YearsAndOverEnrolledInSchoolMale3YearsAndOverEnrolledInSchoolPercentEnrolledInCollegeOrGraduateSchoolInPercent,
seop.Female AS SCHOOLEnrollmentPeople3YearsAndOverEnrolledInSchoolFemale3YearsAndOverEnrolledInSchool,
seop.FemaleEnrolledInKindergartenToGrade12InPercent AS SCHOOLEnrollmentPeople3YearsAndOverEnrolledInSchoolFemale3YearsAndOverEnrolledInSchoolPercentEnrolledInKindergartenToGrade12InPercent,
seop.FemaleEnrolledInCollegeOrGraduateSchoolInPercent AS SCHOOLEnrollmentPeople3YearsAndOverEnrolledInSchoolFemale3YearsAndOverEnrolledInSchoolPercentEnrolledInCollegeOrGraduateSchoolInPercent,
eaop.EducationalAttainmentOfPeople25YearsAndOver AS EDUCATIONALAttainmentPeople25YearsAndOver,
eaop.LessThanHighSchoolDiplomaInPercent AS EDUCATIONALAttainmentPeople25YearsAndOverLessThanHighSchoolDiplomaInPercent,
eaop.HighSchoolGraduate_IncludesEquivalency_InPercent AS EDUCATIONALAttainmentPeople25YearsAndOverHighSchoolGraduate_IncludesEquivalency_InPercent,
eaop.SomeCollegeOrAssociateSDegreeInPercent AS EDUCATIONALAttainmentPeople25YearsAndOverSomeCollegeOrAssociateSDegreeInPercent,
eaop.BachelorSDegreeInPercent AS EDUCATIONALAttainmentPeople25YearsAndOverBachelorSDegreeInPercent,
eaop.GraduateOrProfessionalDegreeInPercent AS EDUCATIONALAttainmentPeople25YearsAndOverGraduateOrProfessionalDegreeInPercent,
eaop.HighSchoolGraduateOrHigherInPercent AS EDUCATIONALAttainmentPeople25YearsAndOverHighSchoolGraduateOrHigherInPercent,
eaop.HighSchoolGraduateOrHigherMaleInPercent AS EDUCATIONALAttainmentPeople25YearsAndOverHighSchoolGraduateOrHigherMaleHighSchoolGraduateOrHigherInPercent,
eaop.HighSchoolGraduateOrHigherFemaleInPercent AS EDUCATIONALAttainmentPeople25YearsAndOverHighSchoolGraduateOrHigherFemaleHighSchoolGraduateOrHigherInPercent,
eaop.BachelorSDegreeOrHigherInPercent AS EDUCATIONALAttainmentPeople25YearsAndOverBachelorSDegreeOrHigherInPercent,
eaop.BachelorSDegreeOrHigherMaleBachelorSDegreeOrHigherInPercent AS EDUCATIONALAttainmentPeople25YearsAndOverBachelorSDegreeOrHigherMaleBachelorSDegreeOrHigherInPercent,
eaop.BachelorSDegreeOrHigherFemaleBachelorSDegreeOrHigherInPercent AS EDUCATIONALAttainmentPeople25YearsAndOverBachelorSDegreeOrHigherFemaleBachelorSDegreeOrHigherInPercent,
fw.FERTILITYWomen15To50Years AS FERTILITYWomen15To50Years,
fw.WhoHadABirthInThePast12Months AS FERTILITYWomen15To50YearsWomen15To50YearsWhoHadABirthInThePast12Months,
fw.WhoHadABirthInThePast12MonthsUnmarried AS FERTILITYWomen15To50YearsWomen15To50YearsWhoHadABirthInThePast12MonthsUnmarriedWomen15To50YearsWhoHadABirthInThePast12Months,
fw.UnmarriedGaveBirthPast12MonthToGivingBirthPercent AS FERTILITYWomen15To50YearsWomen15To50YearsWhoHadABirthInThePast12MonthsUnmarriedWomen15To50YearsWhoHadABirthInThePast12MonthsAsAPercentOfAllWomenWithABirthInThePast12MonthsInPercent,
gpr.GrandParents AS RESPONSIBILITYForGrandchildrenUnder18YearsPeople30YearsAndOver,
gpr.LivingWithGrandchildrenInPercent AS RESPONSIBILITYForGrandchildrenUnder18YearsPeople30YearsAndOverGrandparentsLivingWithGrandchild_Ren_InPercent,
gpr.LivingWithGrandchildAsPercentOfGrandParentPercent AS RESPONSIBILITYForGrandchildrenUnder18YearsPeople30YearsAndOverGrandparentsLivingWithGrandchild_Ren_GrandparentsResponsibleForGrandchildrenAsAPercentOfLivingWithGrandchildrenInPercent,
vts.CivilianPeople18YearsAndOver AS VETERANStatusCivilianPeople18YearsAndOver,
vts. CivilianPeople18YearsAndOverCivilianVeteranInPercent AS VETERANStatusCivilianPeople18YearsAndOverCivilianVeteranInPercent,
dsni.People AS DISABILITYStatusTotalCivilianNoninstitutionalizedPeople,
dsni.PeopleWithADisabilityInPercent AS DISABILITYStatusTotalCivilianNoninstitutionalizedPeopleWithADisabilityInPercent,
dsni.CivilianPeopleUnder18Years AS DISABILITYStatusCivilianNoninstitutionalizedPeopleUnder18Years,
dsni.CivilianPeopleUnder18YearsWithADisabilityInPercent AS DISABILITYStatusCivilianNoninstitutionalizedPeopleUnder18YearsWithADisabilityInPercent,
dsni.CivilianPeople18To64Years AS DISABILITYStatusCivilianNoninstitutionalizedPeople18To64Years,
dsni.CivilianPeople18To64YearsWithADisabilityInPercent AS DISABILITYStatusCivilianNoninstitutionalizedPeople18To64YearsWithADisabilityInPercent,
dsni.CivilianPeople65YearsAndOlder AS DISABILITYStatusCivilianNoninstitutionalizedPeople65YearsAndOlder,
dsni.CivilianPeople65YearsAndOlderWithADisabilityInPercent AS DISABILITYStatusCivilianNoninstitutionalizedPeople65YearsAndOlderWithADisabilityInPercent,
ryap.People1YearAndOver AS RESIDENCE1YearAgoPeople1YearAndOver,
ryap.SameHouseInPercent AS RESIDENCE1YearAgoPeople1YearAndOverSameHouseInPercent,
ryap.DifferentHouseInTheUSInPercent AS RESIDENCE1YearAgoPeople1YearAndOverDifferentHouseInTheUSInPercent,
ryap.DifferentHouseInTheUSSameCountyInPercent AS RESIDENCE1YearAgoPeople1YearAndOverDifferentHouseInTheUSSameCountyInPercent,
ryap.DifferentHouseInTheUSDifferentCountyInPercent AS RESIDENCE1YearAgoPeople1YearAndOverDifferentHouseInTheUSDifferentCountyInPercent,
ryap.DifferentHouseInTheUSDiffCountySameStateInPercent AS RESIDENCE1YearAgoPeople1YearAndOverDifferentHouseInTheUSDifferentCountySameStateInPercent,
ryap.DifferentHouseInUSDifferCountyDifferStatePercent AS RESIDENCE1YearAgoPeople1YearAndOverDifferentHouseInTheUSDifferentCountyDifferentStateInPercent,
ryap.RESIDENCE1YearAgoPeople1YearAndOverAbroadPercent AS RESIDENCE1YearAgoPeople1YearAndOverAbroadInPercent,
bpc.BirthPlaceCitizenshipStatusAndYearOfEntryNative AS BirthPlaceCitizenshipStatusAndYearOfEntryNative,
bpc.NativeMaleInPercent AS BirthPlaceCitizenshipStatusAndYearOfEntryNativeMaleInPercent,
bpc.NativeFemaleInPercent AS BirthPlaceCitizenshipStatusAndYearOfEntryNativeFemaleInPercent,
bpc.ForeignBorn AS BirthPlaceCitizenshipStatusAndYearOfEntryForeignBorn,
bpc.ForeignBornMaleInPercent AS BirthPlaceCitizenshipStatusAndYearOfEntryForeignBornMaleInPercent,
bpc.ForeignBornFemaleInPercent AS BirthPlaceCitizenshipStatusAndYearOfEntryForeignBornFemaleInPercent,
bpc.ForeignBornForeignBorn_NaturalizedUSCitizen AS BirthPlaceCitizenshipStatusAndYearOfEntryForeignBornForeignBorn_NaturalizedUSCitizen,
bpc.ForeignBorn_NaturalizedUSCitizenMaleInPercent AS BirthPlaceCitizenshipStatusAndYearOfEntryForeignBornForeignBorn_NaturalizedUSCitizenMaleInPercent,
bpc.ForeignBorn_NaturalizedUSCitizenFemaleInPercent AS BirthPlaceCitizenshipStatusAndYearOfEntryForeignBornForeignBorn_NaturalizedUSCitizenFemaleInPercent,
bpc.ForeignBorn_NotAUSCitizen AS BirthPlaceCitizenshipStatusAndYearOfEntryForeignBornForeignBorn_NotAUSCitizen,
bpc.ForeignBorn_NotAUSCitizenMaleInPercent AS BirthPlaceCitizenshipStatusAndYearOfEntryForeignBornForeignBorn_NotAUSCitizenMaleInPercent,
bpc.ForeignBorn_NotAUSCitizenFemaleInPercent AS BirthPlaceCitizenshipStatusAndYearOfEntryForeignBornForeignBorn_NotAUSCitizenFemaleInPercent,
bpc.PeopleBornOutsideTheUnitedStates AS BirthPlaceCitizenshipStatusAndYearOfEntryPeopleBornOutsideTheUnitedStates,
bpc.PeopleBornOutsideUSEntered2010OrLaterInPercent AS BirthPlaceCitizenshipStatusAndYearOfEntryPeopleBornOutsideTheUnitedStatesEntered2010OrLaterInPercent,
bpc.PeopleBornOutsideUSEntered2000To2009InPercent AS BirthPlaceCitizenshipStatusAndYearOfEntryPeopleBornOutsideTheUnitedStatesEntered2000To2009InPercent,
bpc.PeopleBornOutsideUSEnteredBefore2000InPercent AS BirthPlaceCitizenshipStatusAndYearOfEntryPeopleBornOutsideTheUnitedStatesEnteredBefore2000InPercent,
wrb.ForeignBornExcludingPeopleBornAtSea AS WORLDRegionOfBirthOfForeignBornForeignBornPeopleExcludingPeopleBornAtSea,
wrb.ForeignBornExcludingPeopleBornAtSeaEuropePercent AS WORLDRegionOfBirthOfForeignBornForeignBornPeopleExcludingPeopleBornAtSeaEuropeInPercent,
wrb.ForeignBornExcludingPeopleBornAtSeaAsiaPercent AS WORLDRegionOfBirthOfForeignBornForeignBornPeopleExcludingPeopleBornAtSeaAsiaInPercent,
wrb.ForeignBornExcludingPeopleBornAtSeaAfricaPercent AS WORLDRegionOfBirthOfForeignBornForeignBornPeopleExcludingPeopleBornAtSeaAfricaInPercent,
wrb.ForeignBornExcludingPeopleBornAtSeaOceaniaPercent AS WORLDRegionOfBirthOfForeignBornForeignBornPeopleExcludingPeopleBornAtSeaOceaniaInPercent,
wrb.ForeignBornExcludingAtSeaLatinAmericaPercent AS WORLDRegionOfBirthOfForeignBornForeignBornPeopleExcludingPeopleBornAtSeaLatinAmericaInPercent,
wrb.ForeignBornExcludingAtSeaNorthernAmericaInPercent AS WORLDRegionOfBirthOfForeignBornForeignBornPeopleExcludingPeopleBornAtSeaNorthernAmericaInPercent,
las.People5YearsAndOver AS LANGUAGESpokenAtHomeAndAbilityToSpeakEnglishPeople5YearsAndOver,
las.People5YearsAndOverEnglishOnlyInPercent AS LANGUAGESpokenAtHomeAndAbilityToSpeakEnglishPeople5YearsAndOverEnglishOnlyInPercent,
las.People5AndOverLanguageOtherThanEnglishInPercent AS LANGUAGESpokenAtHomeAndAbilityToSpeakEnglishPeople5YearsAndOverLanguageOtherThanEnglishInPercent,
las.People5AndOverSpeakEngLessThanVeryWellInPercent AS LANGUAGESpokenAtHomeAndAbilityToSpeakEnglishPeople5YearsAndOverLanguageOtherThanEnglishSpeakEnglishLessThanVeryWellInPercent,
esp.EMPLOYMENTStatusPeople16YearsAndOver AS EMPLOYMENTStatusPeople16YearsAndOver,
esp.InLaborForceInPercent AS EMPLOYMENTStatusPeople16YearAndOverInLaborForceInPercent,
esp.InLaborForceCivilianLaborForceInPercent AS EMPLOYMENTStatusPeople16YearsAndOverInLaborForceCivilianLaborForceInPercent,
esp.InLaborForceCivilianLaborForceEmployedInPercent AS EMPLOYMENTStatusPeople16YearsAndOverInLaborForceCivilianLaborForceEmployedInPercent,
esp.InLaborForceCivilianLaborForceUnemployedInPercent AS EMPLOYMENTStatusPeople16YearsAndOverInLaborForceCivilianLaborForceUnemployedInPercent,
esp.InLaborForceCivilianLFUnemploymentRateInPercent AS EMPLOYMENTStatusPeople16YearsAndOverInLaborForceCivilianLaborForceUnemployedUnemploymentRateInPercent,
esp.InLaborForceArmedForcesInPercent AS EMPLOYMENTStatusPeople16YearsAndOverInLaborForceArmedForcesInPercent,
esp.NotInLaborForceInPercent AS EMPLOYMENTStatusPeople16YearsAndOverNotInLaborForceInPercent,
esp.Females AS EMPLOYMENTStatusFemales16YearsAndOver,
esp.FemalesInLaborForceInPercent AS EMPLOYMENTStatusFemales16YearsAndOverInLaborForceInPercent,
esp.FemalesInLaborForceCivilianLaborForceInPercent AS EMPLOYMENTStatusFemales16YearsAndOverInLaborForceCivilianLaborForceInPercent,
esp.FemalesInLaborForceCivilianLFEmployedPercent AS EMPLOYMENTStatusFemales16YearsAndOverInLaborForceCivilianLaborForceEmployedInPercent,
esp.FemalesInLaborForceCivilianLFUnemployedInPercent AS EMPLOYMENTStatusFemales16YearsAndOverInLaborForceCivilianLaborForceUnemployedInPercent,
esp.FemalesInCivilianLaborForceUnemployedRatePercent AS EMPLOYMENTStatusFemales16YearsAndOverInLaborForceCivilianLaborForceUnemployedUnemploymentRateInPercent,
ctw.Workers AS COMMUTINGToWorkWorkers16YearsAndOver,
ctw.WorkersCarTruckOrVan_DroveAloneInPercent AS COMMUTINGToWorkWorkers16YearsAndOverCarTruckOrVan_DroveAloneInPercent,
ctw.WorkersCarTruckOrVan_CarpooledInPercent AS COMMUTINGToWorkWorkers16YearsAndOverCarTruckOrVan_CarpooledInPercent,
ctw.WorkersPublicTransportationExcludingTaxiInPercent AS COMMUTINGToWorkWorkers16YearsAndOverPublicTransportation_ExcludingTaxicab_InPercent,
ctw.WorkersWalkedInPercent AS COMMUTINGToWorkWorkers16YearsAndOverWalkedInPercent,
ctw.WorkersOtherMeansInPercent AS COMMUTINGToWorkWorkers16YearsAndOverOtherMeansInPercent,
ctw.WorkersWorkedFromHomeInPercent AS COMMUTINGToWorkWorkers16YearsAndOverWorkedFromHomeInPercent,
ctw.WorkersMeanTravelTimeToWork_Minutes AS COMMUTINGToWorkWorkers16YearsAndOverMeanTravelTimeToWork_Minutes,
oce.People AS OCCUPATIONCivilianEmployedPeople16YearsAndOver,
oce.PeopleManagementBusinessScienceAndArtsInPercent AS OCCUPATIONCivilianEmployedPeople16YearsAndOverManagementBusinessScienceAndArtsOccupationsInPercent,
oce.PeopleServiceInPercent AS OCCUPATIONCivilianEmployedPeople16YearsAndOverServiceOccupationsInPercent,
oce.PeopleSalesAndOfficeInPercent AS OCCUPATIONCivilianEmployedPeople16YearsAndOverSalesAndOfficeOccupationsInPercent,
oce.PeopleNaturalResourcesConstructionInPercent AS OCCUPATIONCivilianEmployedPeople16YearsAndOverNaturalResourcesConstructionAndMaintenanceOccupationsInPercent,
oce.PeopleProductionTransportationInPercent AS OCCUPATIONCivilianEmployedPeople16YearsAndOverProductionTransportationAndMaterialMovingOccupationsInPercent,
oce.Male AS OCCUPATIONMaleCivilianEmployedPeople16YearsAndOver,
oce.MaleManagementBusinessScienceAndArtsInPercent AS OCCUPATIONMaleCivilianEmployedPeople16YearsAndOverManagementBusinessScienceAndArtsOccupationsInPercent,
oce.MaleServiceInPercent AS OCCUPATIONMaleCivilianEmployedPeople16YearsAndOverServiceOccupationsInPercent,
oce.MaleSalesAndOfficeInPercent AS OCCUPATIONMaleCivilianEmployedPeople16YearsAndOverSalesAndOfficeOccupationsInPercent,
oce.MaleNaturalResourcesConstructionInPercent AS OCCUPATIONMaleCivilianEmployedPeople16YearsAndOverNaturalResourcesConstructionAndMaintenanceOccupationsInPercent,
oce.MaleProductionTransportationInPercent AS OCCUPATIONMaleCivilianEmployedPeople16YearsAndOverProductionTransportationAndMaterialMovingOccupationsInPercent,
oce.Female AS OCCUPATIONFemaleCivilianEmployedPeople16YearsAndOver,
oce.FemaleManagementBusinessScienceAndArtsInPercent AS OCCUPATIONFemaleCivilianEmployedPeople16YearsAndOverManagementBusinessScienceAndArtsOccupationsInPercent,
oce.FemaleServiceInPercent AS OCCUPATIONFemaleCivilianEmployedPeople16YearsAndOverServiceOccupationsInPercent,
oce.FemaleSalesAndOfficeInPercent AS OCCUPATIONFemaleCivilianEmployedPeople16YearsAndOverSalesAndOfficeOccupationsInPercent,
oce.FemaleNaturalResourcesConstructionInPercent AS OCCUPATIONFemaleCivilianEmployedPeople16YearsAndOverNaturalResourcesConstructionAndMaintenanceOccupationsInPercent,
oce.FemaleProductionTransportationInPercent AS OCCUPATIONFemaleCivilianEmployedPeople16YearsAndOverProductionTransportationAndMaterialMovingOccupationsInPercent,
ice.People AS INDUSTRYCivilianEmployedPeople16YearsAndOver,
ice.AgricultureForestryFishingHuntingMiningInPercent AS INDUSTRYCivilianEmployedPeople16YearsAndOverAgricultureForestryFishingAndHuntingAndMiningInPercent,
ice.ConstructionInPercent AS INDUSTRYCivilianEmployedPeople16YearsAndOverConstructionInPercent,
ice.ManufacturingInPercent AS INDUSTRYCivilianEmployedPeople16YearsAndOverManufacturingInPercent,
ice.WholesaleTradeInPercent AS INDUSTRYCivilianEmployedPeople16YearsAndOverWholesaleTradeInPercent,
ice.RetailTradeInPercent AS INDUSTRYCivilianEmployedPeople16YearsAndOverRetailTradeInPercent,
ice.TransportationAndWarehousingAndUtilitiesInPercent AS INDUSTRYCivilianEmployedPeople16YearsAndOverTransportationAndWarehousingAndUtilitiesInPercent,
ice.InformationInPercent AS INDUSTRYCivilianEmployedPeople16YearsAndOverInformationInPercent,
ice.FinanceInsuranceRealEstateRentalLeasingInPercent AS INDUSTRYCivilianEmployedPeople16YearsAndOverFinanceAndInsuranceAndRealEstateAndRentalAndLeasingInPercent,
ice.ScientificManagementAdministrativeMgmtInPercent AS INDUSTRYCivilianEmployedPeople16YearsAndOverProfessionalScientificAndManagementAndAdministrativeAndWasteManagementServicesInPercent,
ice.EducationalServicesHealthCareAssistanceInPercent AS INDUSTRYCivilianEmployedPeople16YearsAndOverEducationalServicesAndHealthCareAndSocialAssistanceInPercent,
ice.ArtsEntertainmentAccommodationFoodServeInPercent AS INDUSTRYCivilianEmployedPeople16YearsAndOverArtsEntertainmentAndRecreationAndAccommodationAndFoodServicesInPercent,
ice.OtherServices_ExceptPublicAdministrationInPercent AS INDUSTRYCivilianEmployedPeople16YearsAndOverOtherServices_ExceptPublicAdministration_InPercent,
ice.PublicAdministrationInPercent AS INDUSTRYCivilianEmployedPeople16YearsAndOverPublicAdministrationInPercent,
cow.People AS CLASSOfWorkerCivilianEmployedPeople16YearsAndOver,
cow.PeoplePrivateWageAndSalaryWorkersInPercent AS CLASSOfWorkerCivilianEmployedPeople16YearsAndOverPrivateWageAndSalaryWorkersInPercent,
cow.PeopleGovernmentWorkersInPercent AS CLASSOfWorkerCivilianEmployedPeople16YearsAndOverGovernmentWorkersInPercent,
cow.PeopleSelfEmployedInOwnNotcorporatBusinessPercent AS CLASSOfWorkerCivilianEmployedPeople16YearsAndOverSelf_EmployedWorkersInOwnNotIncorporatedBusinessInPercent,
cow.PeopleUnpaidFamilyWorkersInPercent AS CLASSOfWorkerCivilianEmployedPeople16YearsAndOverUnpaidFamilyWorkersInPercent,
itp.Households AS INCOMEInThePast12Months_PastYearInflation_AdjustedDollars_Households,
itp.HouseholdsMedianHouseholdIncome AS INCOMEInThePast12Months_PastYearInflation_AdjustedDollars_HouseholdsMedianHouseholdIncome_Dollars_,
itp.HouseholdsWithEarningsInPercent AS INCOMEInThePast12Months_PastYearInflation_AdjustedDollars_HouseholdsWithEarningsInPercent,
itp.HouseholdsWithEarningsMeanEarnings AS INCOMEInThePast12Months_PastYearInflation_AdjustedDollars_HouseholdsWithEarningsMeanEarnings_Dollars_,
itp.HouseholdsWithSocialSecurityIncomeInPercent AS INCOMEInThePast12Months_PastYearInflation_AdjustedDollars_HouseholdsWithSocialSecurityIncomeInPercent,
itp.HouseholdsWithSocialSecurityIncomeMeanSSIncome AS INCOMEInThePast12Months_PastYearInflation_AdjustedDollars_HouseholdsWithSocialSecurityIncomeMeanSocialSecurityIncome_Dollars_,
itp.HouseholdsWithSupplementalSecurityIncomeInPercent AS INCOMEInThePast12Months_PastYearInflation_AdjustedDollars_HouseholdsWithSupplementalSecurityIncomeInPercent,
itp.HouseholdsWithSupplementalSecurityIncomeMeanSI AS INCOMEInThePast12Months_PastYearInflation_AdjustedDollars_HouseholdsWithSupplementalSecurityIncomeMeanSupplementalSecurityIncome_Dollars_,
itp.HouseholdsWithCashPublicAssistanceIncomeInPercent AS INCOMEInThePast12Months_PastYearInflation_AdjustedDollars_HouseholdsWithCashPublicAssistanceIncomeInPercent,
itp.HouseholdsWithCashPublicAssistanceIncomeMeanCPAI AS INCOMEInThePast12Months_PastYearInflation_AdjustedDollars_HouseholdsWithCashPublicAssistanceIncomeMeanCashPublicAssistanceIncome_Dollars_,
itp.HouseholdsWithRetirementIncomeInPercent AS INCOMEInThePast12Months_PastYearInflation_AdjustedDollars_HouseholdsWithRetirementIncomeInPercent,
itp.HouseholdsWithRetirementIncomeMeanRI AS INCOMEInThePast12Months_PastYearInflation_AdjustedDollars_HouseholdsWithRetirementIncomeMeanRetirementIncome_Dollars_,
itp.HouseholdsWithFoodStampOrSnapBenefitsInPercent AS INCOMEInThePast12Months_PastYearInflation_AdjustedDollars_HouseholdsWithFoodStampOrSnapBenefitsInPercent,
itp.Families AS INCOMEInThePast12Months_PastYearInflation_AdjustedDollars_Families,
itp.FamiliesMedianFamilyIncome AS INCOMEInThePast12Months_PastYearInflation_AdjustedDollars_FamiliesMedianFamilyIncome_Dollars_,
itp.FamiliesMedianFamilyIncomeMarriedCopFamilyPercent AS INCOMEInThePast12Months_PastYearInflation_AdjustedDollars_FamiliesMedianFamilyIncome_Dollars_Married_CoupleFamilyInPercent,
itp.FamiliesMedianIncome AS INCOMEInThePast12Months_PastYearInflation_AdjustedDollars_FamiliesMedianIncome_Dollars_,
itp.FamiliesMedianIncomeMaleNoSpousePresentInPercent AS INCOMEInThePast12Months_PastYearInflation_AdjustedDollars_FamiliesMedianIncome_Dollars_MaleHouseholderNoSpousePresentFamilyInPercent,
itp.FamiliesMedianIncome_1 AS INCOMEInThePast12Months_PastYearInflation_AdjustedDollars_FamiliesMedianIncome_Dollars_1,
itp.FamiliesMedianIncomeFemaleNoSpousePresentPercent AS INCOMEInThePast12Months_PastYearInflation_AdjustedDollars_FamiliesMedianIncome_Dollars_FemaleHouseholderNoHusbandPresentFamilyInPercent,
itp.FamiliesMedianIncome_2 AS INCOMEInThePast12Months_PastYearInflation_AdjustedDollars_FamiliesMedianIncome_Dollars_2,
itp.Individuals AS INCOMEInThePast12Months_PastYearInflation_AdjustedDollars_Individuals,
itp.IndividualsPerCapitaIncome AS INCOMEInThePast12Months_PastYearInflation_AdjustedDollars_IndividualsPerCapitaIncome_Dollars_,
itp.IndividualsWithEarningsForFullYearWorkersToMale AS INCOMEInThePast12Months_PastYearInflation_AdjustedDollars_IndividualsWithEarningsForFull_TimeYear_RoundWorkersToMale,
itp.IndividualsWithEarningsForFullYearWorkersToFemale AS INCOMEInThePast12Months_PastYearInflation_AdjustedDollars_IndividualsWithEarningsForFull_TimeYear_RoundWorkersToFemale,
itp.IndividualsMeanEarningsForFullYearWorkersToMale AS INCOMEInThePast12Months_PastYearInflation_AdjustedDollars_IndividualsMeanEarnings_Dollars_ForFull_TimeYear_RoundWorkersToMale,
itp.IndividualsMeanEarningsForFullYearWorkersToFemale AS INCOMEInThePast12Months_PastYearInflation_AdjustedDollars_IndividualsMeanEarnings_Dollars_ForFull_TimeYear_RoundWorkersToFemale,
itp.IndividualsMedianEarningsFullYearWorkersToMale AS INCOMEInThePast12Months_PastYearInflation_AdjustedDollars_IndividualsMedianEarnings_Dollars_Full_TimeYear_RoundWorkersToMale,
itp.IndividualsMedianEarningsFullYearWorkersToFemale AS INCOMEInThePast12Months_PastYearInflation_AdjustedDollars_IndividualsMedianEarnings_Dollars_Full_TimeYear_RoundWorkersToFemale,
hic.NoninstitutionalizedPeople AS HEALTHInsuranceCoverageCivilianNoninstitutionalizedPeople,
hic.NoninstitutionalPeopPrivateHealthInsurancePercent AS HEALTHInsuranceCoverageCivilianNoninstitutionalizedPeopleWithPrivateHealthInsuranceInPercent,
hic.NoninstitutionalPeopleWithPublicCoverageInPercent AS HEALTHInsuranceCoverageCivilianNoninstitutionalizedPeopleWithPublicCoverageInPercent,
hic.NoninstitutionalPeopNoHealthInsuranceCoverPercent AS HEALTHInsuranceCoverageCivilianNoninstitutionalizedPeopleNoHealthInsuranceCoverageInPercent,
pro.AllFamiliesInPercent AS POVERTYRatesForFamiliesAndPeopleForWhomPovertyStatusIsDeterminedAllFamiliesInPercent,
pro.AllFamiliesWithChildrenOfTheHouseholder AS POVERTYRatesForFamiliesAndPeopleForWhomPovertyStatusIsDeterminedAllFamiliesWithRelatedChildrenOfTheHouseholderUnder18YearsInPercent,
pro.AllFamiliesWithChildrenToUnder5YearsInPercent AS POVERTYRatesForFamiliesAndPeopleForWhomPovertyStatusIsDeterminedAllFamiliesWithRelatedChildrenOfTheHouseholderUnder18YearsWithRelatedChildrenOfTheHouseholderUnder5YearsOnlyInPercent,
pro.Married_CoupleFamilyInPercent AS POVERTYRatesForFamiliesAndPeopleForWhomPovertyStatusIsDeterminedAllFamiliesMarried_CoupleFamilyInPercent,
pro.Married_CoupleFamilyWithChildrenInPercent AS POVERTYRatesForFamiliesAndPeopleForWhomPovertyStatusIsDeterminedAllFamiliesMarried_CoupleFamilyWithRelatedChildrenOfTheHouseholderUnder18YearsInPercent,
pro.Married_CoupleFamilyWithChildToUnde5YearInPercent AS POVERTYRatesForFamiliesAndPeopleForWhomPovertyStatusIsDeterminedAllFamiliesMarried_CoupleFamilyWithRelatedChildrenOfTheHouseholderUnder18YearsWithRelatedChildrenOfTheHouseholderUnder5YearsOnlyInPercent,
pro.FemaleHouseholderNoSpouseFamilyInPercent AS POVERTYRatesForFamiliesAndPeopleForWhomPovertyStatusIsDeterminedAllFamiliesFemaleHouseholderNoSpousePresentFamilyInPercent,
pro.FemaleHouseholderNoSpouseFamilyWithChildInPercent AS POVERTYRatesForFamiliesAndPeopleForWhomPovertyStatusIsDeterminedAllFamiliesFemaleHouseholderNoSpousePresentFamilyWithRelatedChildrenOfTheHouseholderUnder18YearsInPercent,
pro.FemaleHouseholderTORelatedChildrenUnder5InPercent AS POVERTYRatesForFamiliesAndPeopleForWhomPovertyStatusIsDeterminedAllFamiliesFemaleHouseholderNoSpousePresentFamilyWithRelatedChildrenOfTheHouseholderUnder18YearsWithRelatedChildrenOfTheHouseholderUnder5YearsOnlyInPercent,
pro.PeopleInPercent AS POVERTYRatesForFamiliesAndPeopleForWhomPovertyStatusIsDeterminedAllPeopleInPercent,
pro.PeopleUnder18YearsInPercent AS POVERTYRatesForFamiliesAndPeopleForWhomPovertyStatusIsDeterminedAllPeopleUnder18YearsInPercent,
pro.PeopleUnder18ChildOfHouseholderUnder18InPercent AS POVERTYRatesForFamiliesAndPeopleForWhomPovertyStatusIsDeterminedAllPeopleUnder18YearsRelatedChildrenOfTheHouseholderUnder18YearsInPercent,
pro.PeopleWithChildrenOfHouseholderToUnder5InPercent AS POVERTYRatesForFamiliesAndPeopleForWhomPovertyStatusIsDeterminedAllPeopleUnder18YearsRelatedChildrenOfTheHouseholderUnder18YearsRelatedChildrenOfTheHouseholderUnder5YearsInPercent,
pro.PeopleWithChildrenTo5To17YearsInPercent AS POVERTYRatesForFamiliesAndPeopleForWhomPovertyStatusIsDeterminedAllPeopleUnder18YearsRelatedChildrenOfTheHouseholderUnder18YearsRelatedChildrenOfTheHouseholder5To17YearsInPercent,
pro.People18YearsAndOverInPercent AS POVERTYRatesForFamiliesAndPeopleForWhomPovertyStatusIsDeterminedAllPeople18YearsAndOverInPercent,
pro.People18YearsAndOver18To64YearsInPercent AS POVERTYRatesForFamiliesAndPeopleForWhomPovertyStatusIsDeterminedAllPeople18YearsAndOver18To64YearsInPercent,
pro.People18YearsAndOver65YearsAndOverInPercent AS POVERTYRatesForFamiliesAndPeopleForWhomPovertyStatusIsDeterminedAllPeople18YearsAndOver65YearsAndOverInPercent,
pro.PeoplePeopleInFamiliesInPercent AS POVERTYRatesForFamiliesAndPeopleForWhomPovertyStatusIsDeterminedAllPeoplePeopleInFamiliesInPercent,
pro.PeopleUnrelatedIndividuals15YearsAndOverInPercent AS POVERTYRatesForFamiliesAndPeopleForWhomPovertyStatusIsDeterminedAllPeopleUnrelatedIndividuals15YearsAndOverInPercent,
ht.OccupiedHousingUnit AS HOUSINGTenureOccupiedHousingUnits,
ht.OccupiedHousingUnitsOwnerOccupiedHousingPercent AS HOUSINGTenureOccupiedHousingUnitsOwner_OccupiedHousingUnitsInPercent,
ht.OccupiedHousingRenterOccupiedHousingPercent AS HOUSINGTenureOccupiedHousingUnitsRenter_OccupiedHousingUnitsInPercent,
ht.OccupiedHousingAverageHouseSizeOfOwnerOccupied AS HOUSINGTenureOccupiedHousingUnitsAverageHouseholdSizeOfOwner_OccupiedUnit,
ht.OccupiedHousingAverageHouseSizeOfRenterOccupied AS HOUSINGTenureOccupiedHousingUnitsAverageHouseholdSizeOfRenter_OccupiedUnit,
uis.OccupiedHousingUnit1 AS UNITSInStructureOccupiedHousingUnits,
uis.OccupiedHousingUnitsUnitDetachedOrAttachedPercent AS UNITSInStructureOccupiedHousingUnits1_UnitDetachedOrAttachedInPercent,
uis.OccupiedHousingUnits2To4UnitsInPercent AS UNITSInStructureOccupiedHousingUnits2To4UnitsInPercent,
uis.OccupiedHousingUnits5OrMoreUnitsInPercent AS UNITSInStructureOccupiedHousingUnits5OrMoreUnitsInPercent,
uis.OccupiedHousingMobileHomeBoatRvVanEtcPercent AS UNITSInStructureOccupiedHousingUnitsMobileHomeBoatRvVanEtcInPercent,
ys.BuiltOccupiedHousingUnits AS YEARStructureBuiltOccupiedHousingUnits,
ys.BuiltOccupiedHousingUnitsBuiltLast5YearsInPercent AS YEARStructureBuiltOccupiedHousingUnitsBuiltLast5YearsInPercent,
ys.BuiltOccupiedHousingUnitsBuiltLast15YearInPercent AS YEARStructureBuiltOccupiedHousingUnitsBuiltLast15YearsInPercent,
ys.BuiltOccupiedHousingUnitsBuilt2000To2009InPercent AS YEARStructureBuiltOccupiedHousingUnitsBuilt2000To2009InPercent,
ys.BuiltOccupiedHousingUnitsBuilt1980To1999InPercent AS YEARStructureBuiltOccupiedHousingUnitsBuilt1980To1999InPercent,
ys.BuiltOccupiedHousingUnitsBuilt1960To1979InPercent AS YEARStructureBuiltOccupiedHousingUnitsBuilt1960To1979InPercent,
ys.BuiltOccupiedHousingUnitsBuilt1940To1959InPercent AS YEARStructureBuiltOccupiedHousingUnitsBuilt1940To1959InPercent,
ys.BuiltOccupiedHousingBuilt1939OrEarlierInPercent AS YEARStructureBuiltOccupiedHousingUnitBuilt1939OrEarlierInPercent,
vao.VEHICLESAvailableOccupiedHousingUnits AS VEHICLESAvailableOccupiedHousingUnits,
vao.VEHICLESAvailableOccupiedHousingNoneInPercent AS VEHICLESAvailableOccupiedHousingUnitsNoneInPercent,
vao.VEHICLESAvailableOccupiedHousing1OrMoreInPercent AS VEHICLESAvailableOccupiedHousingUnits1OrMoreInPercent,
hhf.HOUSEHeatingFuelOccupiedHousingUnits AS HOUSEHeatingFuelOccupiedHousingUnits,
hhf.HOUSEHeatingFuelOccupiedHousingUnitsGasInPercent AS HOUSEHeatingFuelOccupiedHousingUnitsGasInPercent,
hhf.HOUSEHeatingFuelOccupiedHousingElectricityPercent AS HOUSEHeatingFuelOccupiedHousingUnitsElectricityInPercent,
hhf.HOUSEHeatingFuelOccupiedHousingAllFuelInPercent AS HOUSEHeatingFuelOccupiedHousingUnitsAllOtherFuelsInPercent,
hhf.HOUSEHeatingFuelOccupiedNoFuelPercent AS HOUSEHeatingFuelOccupiedHousingUnitsNoFuelUsedInPercent,
sc.OccupiedHousingUnits2To4UnitsPercent AS SELECTEDCharacteristicsOccupiedHousingUnits,
sc.OccupiedHousingUnitNoTelephoneAvailableInPercent AS SELECTEDCharacteristicsOccupiedHousingUnitsNoTelephoneServiceAvailableInPercent,
sc.OccupiedHousingUnit10OrMorePerRoomInPercent AS SELECTEDCharacteristicsOccupiedHousingUnits101OrMoreOccupantsPerRoomInPercent,
smo.HousingMortgagExcludingWhereSmocCannotBeComputed AS SELECTEDMonthlyOwnerCostsAsAPercentOfHouseholdIncomeInThePast12MonthsHousingUnitsWithAMortgage_ExcludingUnitsWhereSmocCannotBeComputed_,
smo.ExcludingWhereSmocCannotBeComputeLessThanPercent AS SELECTEDMonthlyOwnerCostsAsAPercentOfHouseholdIncomeInThePast12MonthsHousingUnitsWithAMortgage_ExcludingUnitsWhereSmocCannotBeComputed_LessThan30PercentInPercent,
smo.ExcludingWhereSmocCannotBeComputed30MorePercent AS SELECTEDMonthlyOwnerCostsAsAPercentOfHouseholdIncomeInThePast12MonthsHousingUnitsWithAMortgage_ExcludingUnitsWhereSmocCannotBeComputed_30PercentOrMoreInPercent,
oco.OccupiedHousingUnits AS OWNERCharacteristicsOwner_OccupiedHousingUnits,
oco.OccupiedHousingUnitsMedianValue AS OWNERCharacteristicsOwner_OccupiedHousingUnitsMedianValue_Dollars_,
oco.OccupiedHousingUnitMedianMonthlyCostsWithAMortgge AS OWNERCharacteristicsOwner_OccupiedHousingUnitsMedianSelectedMonthlyOwnerCostsWithAMortgage_Dollars_,
oco.OccupiedHousingMedianMonthlyCostWithoutAMrtgge AS OWNERCharacteristicsOwner_OccupiedHousingUnitsMedianSelectedMonthlyOwnerCostsWithoutAMortgage_Dollars_,
gra.ExcludingWhereGrapiCannotBeComputed AS GROSSRentAsAPercentOfHouseholdIncomeInThePast12MonthsOccupiedUnitsPayingRent_ExcludingUnitsWhereGrapiCannotBeComputed_,
gra.ExcludingWhereGrapiCannotBeComptdLessThn30Percent AS GROSSRentAsAPercentOfHouseholdIncomeInThePast12MonthsOccupiedUnitsPayingRent_ExcludingUnitsWhereGrapiCannotBeComputed_LessThan30PercentInPercent,
gra.ExcludingWhereGrapiCannotBeComputed30OrMorPercent AS GROSSRentAsAPercentOfHouseholdIncomeInThePast12MonthsOccupiedUnitsPayingRent_ExcludingUnitsWhereGrapiCannotBeComputed_30PercentOrMoreInPercent,
gr.OccupiedUnitsPayingRent AS GROSSRentOccupiedUnitsPayingRent,
gr.OccupiedUnitsPayingRentMedian_Dollars_ AS GROSSRentOccupiedUnitsPayingRentMedianGrossRent_Dollars_,
caiu.TotalHouseholds AS COMPUTERSAndInternetUseTotalHouseholds,
caiu.TotalHouseholdsWithAComputerInPercent AS COMPUTERSAndInternetUseTotalHouseholdsWithAComputerInPercent,
caiu.TotalHouseWithAInternetSubscriptionInPercent AS COMPUTERSAndInternetUseTotalHouseholdsWithABroadbandInternetSubscriptionInPercent,
tap.Year_2008 AS LastFourthElection_Republican,
tap.Year_2012 AS LastThirdElection_Republican,
tap.Year_2016 AS LastSecondElection_Republican,
tap.Year_2020 AS LastElection_Republican,
tap.leader_mode AS Poll,
tap.leader_mode AS poll0,
tap.leader_mode AS poll1,
tap.leader_mode AS poll2,
tap.leader_mode AS poll3,
tap.leader_mode AS poll4,
tap.leader_mode AS poll5,
tap.leader_mode AS poll6,
tap.Target AS Target
            FROM `ovalofficeproject.ovaloffice.TOTALNumberOfRaces` tnr
            JOIN `ovalofficeproject.ovaloffice.SEXAndAge` saa ON tnr.CensusYear = saa.CensusYear AND tnr.State_Id = saa.State_Id
            JOIN `ovalofficeproject.ovaloffice.Relationship` rel ON saa.State_Id = rel.State_Id AND saa.CensusYear = rel.CensusYear
            JOIN `ovalofficeproject.ovaloffice.HouseholdsByTypeHouseholds` hbt ON rel.CensusYear = hbt.CensusYear AND rel.State_id = hbt.State_Id
            JOIN `ovalofficeproject.ovaloffice.MaritalStatus` mar ON mar.CensusYear = hbt.CensusYear AND mar.State_id = hbt.State_Id
            JOIN `ovalofficeproject.ovaloffice.SchoolEnrollmentOfPeople3YearsAndAbove` seop ON mar.CensusYear = seop.CensusYear AND mar.State_id = seop.State_Id
            JOIN `ovalofficeproject.ovaloffice.EducationalAttainmentOfPeople25YearsAndOver` eaop ON eaop.CensusYear = seop.CensusYear AND eaop.State_id = seop.State_Id
            JOIN `ovalofficeproject.ovaloffice.FERTILITYWomen15To50Years` fw ON eaop.CensusYear = fw.CensusYear AND eaop.State_id = fw.State_Id
            JOIN `ovalofficeproject.ovaloffice.Grandparent30YearsAndOverResponsibilityForUnder18Years` gpr ON gpr.CensusYear = fw.CensusYear AND gpr.State_id = fw.State_Id
            JOIN `ovalofficeproject.ovaloffice.VeteranStatus` vts ON gpr.CensusYear = vts.CensusYear AND gpr.State_id = vts.State_Id
            JOIN `ovalofficeproject.ovaloffice.DisabilityStatuNonInstitutionalized` dsni ON dsni.CensusYear = vts.CensusYear AND dsni.State_id = vts.State_Id
            JOIN `ovalofficeproject.ovaloffice.Residence1YearAgoPeopleLiving1YearAndOver` ryap ON dsni.CensusYear = ryap.CensusYear AND dsni.State_id = ryap.State_Id
            JOIN `ovalofficeproject.ovaloffice.BirthPlaceCitizenshipStatus` bpc ON bpc.CensusYear = ryap.CensusYear AND bpc.State_id = ryap.State_Id
            JOIN `ovalofficeproject.ovaloffice.WorldRegionOfBirthOfForeignPeople` wrb ON bpc.CensusYear = wrb.CensusYear AND bpc.State_id = wrb.State_Id
            JOIN `ovalofficeproject.ovaloffice.LanguageSpokenAtHomeAndAbilitytoSpeakEnglish` las ON las.CensusYear = wrb.CensusYear AND las.State_id = wrb.State_Id
            JOIN `ovalofficeproject.ovaloffice.EmploymentStatusPeople16YearsAndOver` esp ON las.CensusYear = esp.CensusYear AND las.State_id = esp.State_Id
            JOIN `ovalofficeproject.ovaloffice.CommutingToWorkPeople16YearsAndOver` ctw ON ctw.CensusYear = esp.CensusYear AND ctw.State_id = esp.State_Id
            JOIN `ovalofficeproject.ovaloffice.OccupationOfCivilianEmployedPeople16YearsAndOver` oce ON ctw.CensusYear = oce.CensusYear AND ctw.State_id = oce.State_Id
            JOIN `ovalofficeproject.ovaloffice.IndustryCivilianEmployedPeople16YearsAndOver` ice ON ice.CensusYear = oce.CensusYear AND ice.State_id = oce.State_Id
            JOIN `ovalofficeproject.ovaloffice.ClassOfWorkerCivilianPeolpe16YearsANdOver` cow ON ice.CensusYear = cow.CensusYear AND ice.State_id = cow.State_Id
            JOIN `ovalofficeproject.ovaloffice.IncomeInThePast12Months_PastYearInflation_AdjustedDollars` itp ON itp.CensusYear = cow.CensusYear AND itp.State_id = cow.State_Id
            JOIN `ovalofficeproject.ovaloffice.HealthInsuranceCoverageCivilianPeople` hic ON itp.CensusYear = hic.CensusYear AND itp.State_id = hic.State_Id
            JOIN `ovalofficeproject.ovaloffice.PovertyRatesOfPeopleWhomPovertyStatusIsDetermined` pro ON pro.CensusYear = hic.CensusYear AND pro.State_id = hic.State_Id
            JOIN `ovalofficeproject.ovaloffice.HousingTenure` ht ON pro.CensusYear = ht.CensusYear AND pro.State_id = ht.State_Id
            JOIN `ovalofficeproject.ovaloffice.UnitsInStructure` uis ON uis.CensusYear = ht.CensusYear AND uis.State_id = ht.State_Id
            JOIN `ovalofficeproject.ovaloffice.YearsStructure` ys ON uis.CensusYear = ys.CensusYear AND uis.State_id = ys.State_Id
            JOIN `ovalofficeproject.ovaloffice.VehiclesAvailableOccupied` vao ON vao.CensusYear = ys.CensusYear AND vao.State_id = ys.State_Id
            JOIN `ovalofficeproject.ovaloffice.HOUSEHeatingFuelOccupied` hhf ON vao.CensusYear = hhf.CensusYear AND vao.State_id = hhf.State_Id
            JOIN `ovalofficeproject.ovaloffice.SELECTEDCharacteristics` sc ON sc.CensusYear = hhf.CensusYear AND sc.State_id = hhf.State_Id
            JOIN `ovalofficeproject.ovaloffice.SELECTEDMonthlyOwnerCostAsInPast12MonthWithMortgage` smo ON sc.CensusYear = smo.CensusYear AND sc.State_id = smo.State_Id
            JOIN `ovalofficeproject.ovaloffice.OWNERCharacteristicsOwner` oco ON oco.CensusYear = smo.CensusYear AND oco.State_id = smo.State_Id
            JOIN `ovalofficeproject.ovaloffice.GrossRentAsAPercentOfIncomeInPast12MonthOccupiedUnitsPayingRent` gra ON oco.CensusYear = gra.CensusYear AND oco.State_id = gra.State_Id
            JOIN `ovalofficeproject.ovaloffice.GrossRent` gr ON gr.CensusYear = gra.CensusYear AND gr.State_id = gra.State_Id
            JOIN `ovalofficeproject.ovaloffice.ComputerAndInternetUse` caiu ON tnr.CensusYear = caiu.CensusYear AND tnr.State_Id = caiu.State_Id
            JOIN `ovalofficeproject.ovaloffice.TargetsAndPolls` tap ON tnr.CensusYear =tap.CensusYear AND tnr.State_Id = tap.State_Id
            Where tnr.CensusYear=2023 ORDER BY State;
        """
        query_job = bq_client.query(query)
        df = query_job.to_dataframe()
        
        # Drop unnecessary columns
        df = df.drop(columns=['State_Id', 'CensusYear'], errors='ignore')

        # Ensure 'state' column exists
        if 'state' not in df.columns:
            raise ValueError("Error: 'state' column is missing.")

        # One-hot encode 'state' column
        df_encoded = pd.get_dummies(df, columns=['state'], prefix='state')

        # Rename columns for consistent state names
        state_replacement_map = {
            'state_New_York': 'state_New York',
            'state_New_Jersey': 'state_New Jersey',
            'state_New_Mexico': 'state_New Mexico',
            'state_New_Hampshire': 'state_New Hampshire',
            'state_North_Carolina': 'state_North Carolina',
            'state_North_Dakota': 'state_North Dakota',
            'state_Rhode_Island': 'state_Rhode Island',
            'state_South_Carolina': 'state_South Carolina',
            'state_South_Dakota': 'state_South Dakota',
            'state_West_Virginia': 'state_West Virginia'
        }
        df_encoded.rename(columns=state_replacement_map, inplace=True)

        # Reorder columns
        state_columns = [col for col in df_encoded.columns if col.startswith('state_')]
        other_columns = [col for col in df_encoded.columns if not col.startswith('state_')]
        df_encoded = pd.concat([df_encoded[state_columns], df_encoded[other_columns]], axis=1)

        # Replace party names with binary values
        party_columns = [
            'LastFourthElection_Republican', 'LastThirdElection_Republican',
            'LastSecondElection_Republican', 'LastElection_Republican',
            'Poll', 'poll0', 'poll1', 'poll2', 'poll3', 'poll4', 'poll5', 'poll6', 'Target'
        ]
        df_encoded[party_columns] = df_encoded[party_columns].replace({'Republican': 1, 'Democratic': 0})

        # Verify feature count
        if df_encoded.shape[1] != 371:
            return f"Error: BigQuery dataset must contain 371 features, but got {df_encoded.shape[1]}."

        # Prepare data for prediction
        if 'Target' not in df_encoded.columns:
            raise ValueError("Error: 'Target' column is missing in the BigQuery dataset.")
        X = df_encoded.drop(columns=['Target'])

        if model is None:
            return "Error: Model is not loaded properly."

        # Make predictions
        predictions = model.predict(X)

        # Map predictions back to state names
        results = {state: int(pred) for state, pred in zip(states_dict.keys(), predictions)}

        # Add DC to the results as Democratic
        results['District of Columbia'] = 0

        # Prepare predictions DataFrame
        df_predictions = pd.DataFrame({
            'state': list(results.keys()),
            'prediction': list(results.values())
        })
        df_predictions['party'] = df_predictions['prediction'].map({0: 'Democrat', 1: 'Republican'})
        df_predictions['seats'] = df_predictions['state'].map(states_dict)

        # One-hot encode state column
        df_predictions = pd.get_dummies(df_predictions, columns=['state'], prefix='state')

        # Reorder columns
        df_predictions = df_predictions[['party', 'prediction', 'seats'] + 
                                         [col for col in df_predictions.columns if col.startswith('state_')]]

        # Summary calculations
        democrat_count = sum(df_predictions['party'] == 'Democrat')
        republican_count = sum(df_predictions['party'] == 'Republican')
        total_states = len(states_dict)

        democrat_seats = df_predictions.loc[df_predictions['party'] == 'Democrat', 'seats'].sum()
        republican_seats = df_predictions.loc[df_predictions['party'] == 'Republican', 'seats'].sum()

        winning_party = "Democrat" if democrat_count > republican_count else "Republican"
        democrat_percentage = (democrat_count / total_states) * 100
        republican_percentage = (republican_count / total_states) * 100

        # Sort Democratic states in ascending order
        democrat_states = sorted([state for state, pred in results.items() if pred == 0])
        republican_states = [state for state, pred in results.items() if pred == 1]

        summary = {
            'total_states': total_states,
            'democrat_count': democrat_count,
            'republican_count': republican_count,
            'winning_party': winning_party,
            'democrat_percentage': democrat_percentage,
            'republican_percentage': republican_percentage,
            'democrat_seats': democrat_seats,
            'republican_seats': republican_seats,
            'democrat_states': democrat_states,
            'republican_states': republican_states,
        }

        # Render results in HTML
        return render_template('result.html', results=results, summary=summary)

    except Exception as e:
        app.logger.error(f"Error during prediction process: {str(e)}")
        return f"An error occurred: {str(e)}"

if __name__ == '__main__':
    logging.basicConfig(level=logging.DEBUG)
    app.run(debug=True)
